
/**
 * Represents a specific segment of text from a larger document.
 * This is the atomic unit retrieved during the RAG process.
 */
export interface DocumentChunk {
  id: string; // Unique identifier for the chunk
  sourceId: string; // ID of the parent document
  content: string; // The actual text content
  metadata: {
    startIndex: number; // Position in original text
    endIndex: number;
  };
}

/**
 * Represents a full document uploaded to the Knowledge Base.
 */
export interface KnowledgeDoc {
  id: string;
  title: string;
  content: string; // Full raw content
  chunks: DocumentChunk[]; // The processed chunks ready for retrieval
  uploadDate: Date;
}

/**
 * Tracks the state of the individual steps in the RAG execution pipeline
 * (Ingestion -> Query Refinement -> Search -> Generation).
 */
export interface AnalysisStep {
  id: string;
  label: string;
  status: 'pending' | 'loading' | 'complete' | 'error';
  detail?: string;
}

/**
 * The final output object containing the trace of the entire RAG operation.
 */
export interface RAGResult {
  originalLog: string; // The raw input from the user
  searchQuery: string; // The cleaned/semantic query generated by AI
  retrievedChunks: DocumentChunk[]; // The context found in the KB
  solution: string; // The final answer generated by the LLM
  timestamp: Date;
}
